name: Maven Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Trigger Jenkins 
        run: |
           echo "${{ secrets.SSH_KEY }}" | base64 -d > /tmp/github_actions_key
             chmod 600 /tmp/github_actions_key
                                          ssh -o StrictHostKeyChecking=no -i /tmp/github_actions_key -p "${{ secrets.PORT }}" "${{ secrets.USERNAME }}@${{ secrets.HOST }}" 'curl -s "http://localhost:8080/job/TomcatDeployment/build?token=github-trigger"'
                                                                                  rm -f /tmp/github_actions_key
      
